
import os


##using ensembl genome through ftp for indices

file = open("Acc.txt")
accessions = file.read()
accessions = accessions.split()


inst_dir = "stringtie"
reference = "Saccharomyces_cerevisiae.R64-1-1.111.gtf" #"Homo_sapiens.GRCh38.105.gtf"
input_dir = "/home/chuma-winner/Rna-seq-BioProject/mapping/bam/" #bam files are stored here that were generated by hisat2
output_dir = "/home/chuma-winner/Rna-seq-BioProject/stringtie/assemblies/" #all the gtf assemblies for each samples are stored here from this script
cores = " -p 5 "  #number of processing threads (CPUs) to use for transcript assembly


for x in accessions:
   
    command = inst_dir + cores + " -G " + reference + " " + input_dir + x + ".bam" + " " + " -o " + output_dir + x + ".gtf"
    print(command + " ....running....")
    os.system(command)


print("All done")
